#!/usr/bin/env zsh

# It's important when using `ln` to use the entire path
ln -sf ~/dotfiles/terminal/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/terminal/zshrc ~/.zshrc

if [ ! -d "~/.tmux/plugins/tpm" ] ; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if ! command -v git >/dev/null 2>&1; then
  echo "Git is not installed. Installing Git."
  brew install git
fi

# Neovim
echo
echo '> Configuring Neovim'
if [ ! $SPIN ]; then
  if ! command -v nvim >/dev/null 2>&1; then
      brew install --HEAD neovim
  fi
  brew install fzf
fi

# create a sym link to the nvim config
ln -sf ~/dotfiles/nvim ~/.config/nvim
if ! test -d ~/.config/wezterm; then
  mkdir -p $HOME/.config/wezterm
fi
ln -sf ~/dotfiles/terminal/wezterm ~/.config/wezterm

nvim --headless "+Lazy! sync" +qa

echo
echo '> Configuring oh-my-zsh'
if test -d ~/.oh-my-zsh; then
    rm -rf ~/.oh-my-zsh
fi
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

mkdir -p $HOME/.oh-my-zsh/custom
cp -r ~/dotfiles/terminal/custom/* ~/.oh-my-zsh/custom/

mkdir -p $HOME/.oh-my-zsh/custom/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

mkdir -p $HOME/.oh-my-zsh/custom/themes
git clone https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k --depth=1

source $ZSH/oh-my-zsh.sh

echo
echo '> Configuring git'
git config --global core.editor nvim
git config --global user.name 'Alex Henkemeier'

echo
echo '> Finalizing 🔍'
source ~/.zshrc
tmux source ~/.tmux.conf &

echo
echo 'Done ✅'
echo

return
