# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# removes goofy space on the right side of the prompt
ZLE_RPROMPT_INDENT=0

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
source ~/dotfiles/terminal/custom/p10k-theme
source ~/dotfiles/terminal/local/zshrc

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='nvim'
 else
   export EDITOR='nvim'
 fi

plugins=(git python macos brew virtualenv zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export GPG_TTY=$(tty)

[ -f /opt/homebrew/bin/brew ] && export PATH=$(`echo brew --prefix`)/bin:$(`echo brew --prefix`)sbin:$PATH
[ -f /opt/homebrew/bin/brew ] && export PATH=$(`echo brew --prefix llvm`)/bin:$PATH

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && { type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; } }
[ -f /opt/minidev/dev.sh ] && source /opt/minidev/dev.sh
[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
[[ -x /opt/rbenv/rbenv ]] && eval $(rbenv init - zsh)

# Android development
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
alias love=/Applications/love.app/Contents/MacOS/love

. /opt/homebrew/opt/asdf/libexec/asdf.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
