require("amhenk.packer")
require("amhenk.telescope")
require("amhenk.set")
require("amhenk.githubearl")
require("amhenk.testit")
require("amhenk.remap")
require("amhenk.command")
require("amhenk.nvim-tree")
